spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:5432/db;
    username: sa
    password:
    mysql:
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect